name: Bug Report 🚩
description: Create a report to help us improve
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out our bug report form."
  - type: input
    id: title
    attributes:
      label: Bug Title
      description: "Write a short, clear title for the bug."
      placeholder: "A concise title for the bug"
    validations:
      required: true
  - type: dropdown
    id: bug-category
    attributes:
      label: Category
      description: "Please select the feature that most closely categorizes the bug."
      options:
        - Environment Manager
        - Quantum Jobs
        - Quantum Devices
        - Compute Manager
        - Code Snippets
        - Omnisearch
        - Quantum Docs
        - qBraid-CLI
        - Other
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: "Please describe the bug you're experiencing."
      placeholder: "Describe the bug in detail here."
    validations:
      required: true
  - type: file
    id: images
    attributes:
      label: Attach Images
      description: "If possible, please attach one or more images that illustrate the issue. This could include screenshots, error messages, or other relevant visuals."
      multiple: true
    validations:
      required: false
